In [1]:
import pandas as pd

In [18]:
 df = pd.read_csv('Police_Department_Incident_Reports__2018_to_Present_20250306.csv')

In [20]:
df.head()

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
0,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023,Wednesday,2023/03/11 03:40:00 PM,125379506374,1253795,236046151,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023,Monday,2023/03/13 11:00:00 AM,125355107041,1253551,230174885,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023,Tuesday,2023/03/14 06:45:00 PM,125402407041,1254024,230176728,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/02/15 03:00:00 AM,2023/02/15,03:00,2023,Wednesday,2023/03/11 04:55:00 PM,125378606372,1253786,236046123,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/13 11:26:00 AM,2023/03/13,11:26,2023,Monday,2023/03/13 01:37:00 PM,125419506244,1254195,236046850,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 937595 entries, 0 to 937594
Data columns (total 35 columns):
 #   Column                                                Non-Null Count   Dtype
---  ------                                                --------------   -----
 0   Incident Datetime                                     937595 non-null  object
 1   Incident Date                                         937595 non-null  object
 2   Incident Time                                         937595 non-null  object
 3   Incident Year                                         937595 non-null  int64
 4   Incident Day of Week                                  937595 non-null  object
 5   Report Datetime                                       937595 non-null  object
 6   Row ID                                                937595 non-null  int64
 7   Incident ID                                           937595 non-null  int64
 8   Incident Number                                       937595 non-null  int64
 9   CAD Number                                            729660 non-null  float64
 10  Report Type Code                                      937595 non-null  object
 11  Report Type Description                               937595 non-null  object
 12  Filed Online                                          183467 non-null  object
 13  Incident Code                                         937595 non-null  int64
 14  Incident Category                                     936513 non-null  object
 15  Incident Subcategory                                  936513 non-null  object
 16  Incident Description                                  937595 non-null  object
 17  Resolution                                            937595 non-null  object
 18  Intersection                                          886236 non-null  object
 19  CNN                                                   886236 non-null  float64
 20  Police District                                       937595 non-null  object
 21  Analysis Neighborhood                                 886030 non-null  object
 22  Supervisor District                                   885764 non-null  float64
 23  Supervisor District 2012                              886098 non-null  float64
 24  Latitude                                              886236 non-null  float64
 25  Longitude                                             886236 non-null  float64
 26  Point                                                 886236 non-null  object
 27  Neighborhoods                                         870897 non-null  float64
 28  ESNCAG - Boundary File                                10365 non-null   float64
 29  Central Market/Tenderloin Boundary Polygon - Updated  125381 non-null  float64
 30  Civic Center Harm Reduction Project Boundary          122644 non-null  float64
 31  HSOC Zones as of 2018-06-05                           197160 non-null  float64
 32  Invest In Neighborhoods (IIN) Areas                   0 non-null       float64
 33  Current Supervisor Districts                          886098 non-null  float64
 34  Current Police Districts                              885291 non-null  float64
dtypes: float64(14), int64(5), object(16)
memory usage: 250.4+ MB

In [22]:
crimesin2024 = df.loc[df['Incident Year']==2024]

In [23]:
crimesin2024.head()

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Longitude,Point,Neighborhoods,ESNCAG - Boundary File,Central Market/Tenderloin Boundary Polygon - Updated,Civic Center Harm Reduction Project Boundary,HSOC Zones as of 2018-06-05,Invest In Neighborhoods (IIN) Areas,Current Supervisor Districts,Current Police Districts
1644,2024/09/05 06:15:00 AM,2024/09/05,06:15,2024,Thursday,2024/09/05 07:10:00 AM,142126304134,1421263,240557895,242490594.0,...,-122.409309,POINT (-122.40930938720703 37.78434753417969),20.0,NaN,1.0,1.0,NaN,NaN,10.0,5.0
2273,2024/08/09 12:00:00 AM,2024/08/09,00:00,2024,Friday,2025/01/23 08:46:00 AM,145657206125,1456572,250043931,250230802.0,...,-122.402855,POINT (-122.4028549194336 37.734073638916016),87.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0
2276,2024/12/12 12:06:00 PM,2024/12/12,12:06,2024,Thursday,2025/01/23 05:00:00 PM,145667164080,1456671,250045131,250232601.0,...,-122.407013,POINT (-122.40701293945312 37.78315734863281),32.0,NaN,NaN,1.0,NaN,NaN,10.0,5.0
2277,2024/11/17 12:30:00 PM,2024/11/17,12:30,2024,Sunday,2024/11/17 05:57:00 PM,144629707026,1446297,246148907,NaN,...,-122.453003,POINT (-122.4530029296875 37.77497100830078),12.0,NaN,NaN,NaN,NaN,NaN,4.0,7.0
2282,2024/11/28 02:00:00 PM,2024/11/28,14:00,2024,Thursday,2024/11/28 03:28:00 PM,144630507026,1446305,246154807,NaN,...,-122.400146,POINT (-122.400146484375 37.78121566772461),32.0,NaN,NaN,NaN,NaN,NaN,10.0,1.0